<?php

/**
 * ImportiRicariche
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class ImportiRicariche extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('importi_ricariche');
        $this->hasColumn('ID', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('orgid', 'integer', 4, array('type' => 'integer','length' => 4,'unsigned' => 0,'primary' => false,'default' => '','notnull' => true,'autoincrement' => false));
        $this->hasColumn('numero_sms', 'integer', 4, array('type' => 'integer', 'length' => 4, 'notnull' => true));
        $this->hasColumn('importo', 'float', null, array('type' => 'float', 'notnull' => true));
    }

}