<?php

/**
 * Permissions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
class Permissions extends Doctrine_Record{
  
  public function setTableDefinition(){
    $this->setTableName('permissions');
    $this->hasColumn('ID', 'integer', 4, array('type' => 'integer', 'length' => 4, 'unsigned' => 1, 'primary' => true, 'autoincrement' => true));
    $this->hasColumn('ID_area', 'integer', 4, array('type' => 'integer', 'length' => 4, 'default' => '', 'notnull' => true));
    $this->hasColumn('sortid', 'integer', 4, array('type' => 'integer', 'length' => 4, 'default' => '', 'notnull' => true));
    $this->hasColumn('name', 'string', 64, array('type' => 'string', 'length' => 64, 'default' => '', 'notnull' => true));
    $this->hasColumn('UIname', 'string', 255, array('type' => 'string', 'length' => 255, 'default' => '', 'notnull' => true));
    $this->hasColumn('type', 'integer', 1, array('type' => 'integer', 'length' => 1, 'default' => '0', 'notnull' => true));
    $this->hasColumn('default_value', 'string', 64, array('type' => 'string', 'length' => 64));
  }
  
  public function setUp(){
   $this->hasOne('Areas', array('local' => 'ID_area','foreign' => 'ID','onDelete' =>'CASCADE'));
   $this->hasMany('RolesPermissions', array ('local' => 'ID', 'foreign' =>'ID_permission',"onDelete"=>"CASCADE"));
  }
}