<?php

/**
 * Province
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Province extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('province');
        $this->hasColumn('ID_provincia', 'string', 4, array('type' => 'string', 'length' => 4, 'primary' => true));
        $this->hasColumn('provincia', 'string', 255, array('type' => 'string', 'length' => 255, 'default' => '', 'notnull' => true));
    }

}