<?php

/**
 * Ricariche
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Ricariche extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('ricariche');
        $this->hasColumn('ID', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('orgid', 'integer', 4, array('type' => 'integer', 'length' => 4, 'notnull' => true));
        $this->hasColumn('data_ricarica', 'timestamp', null, array('type' => 'timestamp', 'notnull' => true));
        $this->hasColumn('numero_sms', 'integer', 4, array('type' => 'integer', 'length' => 4, 'notnull' => true));
        $this->hasColumn('importo', 'float', null, array('type' => 'float', 'notnull' => true));
    }
    
    public function setUp(){
      $this->hasOne('Organizations', array ('local' => 'orgid', 'foreign' =>'orgid'));
    }
}