<?php

/**
 * RolesPermissions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
class RolesPermissions extends Doctrine_Record{
  
  public function setTableDefinition(){
    $this->setTableName('roles_permissions');
    $this->hasColumn('ID', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
    $this->hasColumn('ID_role', 'integer', 4, array('type' => 'integer', 'length' => 4, 'default' => '', 'notnull' => true));
    $this->hasColumn('ID_permission', 'integer', 4, array('type' => 'integer', 'length' => 4, 'unsigned' => 1, 'default' => '', 'notnull' => true));
    $this->hasColumn('value', 'string', 64, array('type' => 'string', 'length' => 64));
  }

  public function setUp(){
    $this->hasOne('Permissions', array('local' => 'ID_permission','foreign' => 'ID','onDelete' =>'CASCADE'));
    $this->hasOne('Roles', array('local' => 'ID_role','foreign' => 'ID'));
  }

}