<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Roles extends Doctrine_Record
{
   public function setTableDefinition()
    {
        $this->setTableName('roles');
        $this->hasColumn('ID', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('role', 'string', 255, array('type' => 'string', 'length' => 255, 'notnull' => true));
        $this->hasColumn('superuser', 'integer', 1, array('type' => 'integer', 'length' => 1, 'default' => '0', 'notnull' => true));
        $this->hasColumn('developer', 'integer', 1, array('type' => 'integer', 'length' => 1, 'default' => '0', 'notnull' => true));
        $this->hasColumn('internal_resource', 'integer', 1, array('type' => 'integer', 'length' => 1, 'default' => '0', 'notnull' => true));
    }

    public function setUp(){
      $this->hasMany('Users', array ('local' => 'ID', 'foreign' =>'ID_role'));
      $this->hasMany('RolesPermissions', array("local" => "ID","foreign" => "ID_role","onDelete"=>"CASCADE"));
    }
}