<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Users extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('users');
        $this->hasColumn('ID', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('ID_role', 'integer', 4, array('type' => 'integer', 'length' => 4, 'default' => '', 'notnull' => true));
        $this->hasColumn('data_iscrizione', 'date', null, array('type' => 'date'));
        $this->hasColumn('nome', 'string', 64, array('type' => 'string', 'length' => 64, 'default' => '', 'notnull' => true));
        $this->hasColumn('cognome', 'string', 64, array('type' => 'string', 'length' => 64, 'default' => '', 'notnull' => true));
        $this->hasColumn('email', 'string', 64, array('type' => 'string', 'length' => 64));
        $this->hasColumn('user', 'string', 64, array('type' => 'string', 'length' => 64, 'default' => '', 'notnull' => true));
        $this->hasColumn('password', 'string', 128, array('type' => 'string', 'length' => 128, 'default' => '', 'notnull' => true));
        $this->hasColumn('active', 'integer', 1, array('type' => 'integer', 'length' => 1, 'default' => '0', 'notnull' => true));
    }
  
  
  public function setUp (){
    $this ->hasOne('Roles as Role', array ('local' => 'ID_role', 'foreign' =>'ID'));
    $this ->hasMany('UsersOrganizations', array ('local' => 'ID', 'foreign' =>'ID_user'));
  }
  
}