<?php

/**
 * UsersOrganizations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class UsersOrganizations extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('users_organizations');
        $this->hasColumn('ID', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true, 'autoincrement' => true));
        $this->hasColumn('orgid', 'integer', 4, array('type' => 'integer', 'length' => 4, 'default' => '', 'notnull' => true));
        $this->hasColumn('ID_user', 'integer', 4, array('type' => 'integer', 'length' => 4, 'default' => '', 'notnull' => true));
        $this->hasColumn('active', 'integer', 1, array('type' => 'integer', 'length' => 1, 'default' => '', 'notnull' => true));
    }

}