<?php $this->assign("menu_item","contatti")?>
<?php $this->assign("title","Mister SMS / Contatti")?>
<style type="text/css">
<!--
.style2 {color: #990000}
-->
</style>

<h1>Contatti</h1>

<p>Powered by <strong>Kinesistemi S.r.l.</strong></p>
<p>Via II giugno 1946, n.12 - Oristano (OR)</p>
<p><em>Tel:</em> 0783 1925288</p>
<br/>
<p><em>Mail:</em><a href="mailto:info@mistersms.it">info@mistersms.it</a></p>