<?php $this->assign("menu_item","home")?>
<?php $this->assign("title","Mister SMS -Il gestore di campagne SMS")?>
<h1>Comunicare con un semplice SMS</h1>
<div style="float:right;padding:0px;margin-left:10px"> 
    <img alt="Mister SMS: Comunicare non è mai stato così facile" src="<?=$this->baseUrl()."/img/sms.jpg"?>" />
</div> 
<h2 style="color:#44B71C;">Una soluzione semplice ed efficace per gestire</h2>
<ul class="list_homepage home_paragraph">
  <li>campagne pubblicitarie</li> 
  <li>campagne informative</li>
  <li>concorsi con coupon elettronico</li>
  <li>invio multiplo di SMS</li>
  <li>personalizzazione del mittente</li>
</ul>
<br/>
<h2 style="color:#44B71C;">Nessun software da installare</h2>
<p class="home_paragraph">Non dovrai installare nessun software, sar&agrave; sufficiente accedere al tuo pannello di controllo all'indirizzo e le credenziali d'accesso che ti saranno fornite all'attivazione del servizio.</p>
<br/>
<h2 style="color:#44B71C;">Consegna dei messaggi garantita</h2>
<p class="home_paragraph">La consegna dei messaggi SMS è garantita grazie al fatto che utilizziamo unicamente <b>messaggi di alta qualità con notifica di consegna</b>.</p>