<?php $this->assign("title","Mister SMS / Contattaci")?>
<?php if (count($this->errors)>0):?>
  <h2>Attenzione! ci sono alcuni errori:</h2>
  <ul class="contact_errors">
  <?php foreach($this->errors as $err):?>
    <li><?php echo $this->escape($err) ?></li>
  <?php endforeach?>
  </ul>
<?php else:?>

  <h1 style="color:green">Grazie per l'interessamento</h1>
  <p>Ti ricontatteremo al pi&ugrave; presto per illustrarti il servizio nel dettaglio!</p>

<?php endif?>