<?php $this->assign("menu_item","offerta")?>
<?php $this->assign("title","Mister SMS / La nostra offerta")?>
<h1>Quanto costa ?</h1>
<p><strong>Mister SMS</strong> ti offre l'opportunit&agrave; di acquistare diversi pacchetti per ricaricare il tuo account</p>
<table class="offerta" cellspacing="0" cellpadding="0">
  <tr>
    <td class="pacchetti"><b>Pacchetto</b></td>
    <td class="costo"><b>Costo</b></td>
  </tr>
  <tr>
    <td class="pacchetti"><p>Pacchetto prova 500 SMS</p></td>
    <td class="costo"><p>€ 49,90</p></td>
  </tr>
  <tr>
    <td class="pacchetti"><p>2.500 SMS</p></td>
    <td class="costo"><p>€ 240,00</p></td>
  </tr>
  <tr>
    <td class="pacchetti"><p>5.000 SMS</p></td>
    <td class="costo"><p>€ 460,00</p></td>
  </tr>
  <tr>
    <td class="pacchetti"><p>10.000 SMS</p></td>
    <td class="costo"><p>€ 850,00</p></td>
  </tr>
  <tr>
    <td class="pacchetti"><p>oltre 10.000</p></td>
    <td class="costo"><p>personalizzato</p></td>
  </tr>
  <tr>
  <tr>
    <td class="pacchetti">&nbsp;</td>
    <td class="costo"><p>&nbsp;</p></td>
  </tr>
  <tr>
    <td class="pacchetti"><p>Servizio importazione contatti</p></td>
    <td class="costo"><p>personalizzato</p></td>
  </tr>
</table>
<br/>
<p>* tutti gli importi sono al netto dell&rsquo;IVA 20%</p>
<br/><br/>
<p><strong>Tramite la semplice form a lato potrai richiedere un immediato contatto da parte del nostro personale commerciale !</strong></p>
<p><strong> Se preferisci puoi contattarci telefonicamente chiamando subito il numero:</strong></p>
<div id="big_phone_number"></div>
