<?php $this->assign("menu_item","servizio")?>
<?php $this->assign("title","Mister SMS / Il nostro servizio")?>
<h1>Il Servizio Mister SMS </h1>


<div style="float:right;padding:4px;margin-left:10px"> 
  <img alt="Mister SMS: Comunicare non è mai stato così facile" src="<?=$this->baseUrl()."/img/busta_verde.jpg"?>" />
</div>  
   
<p>Soluzione “chiavi in mano” per <b>l’invio in massa di SMS pubblicitari/informativi</b> ad elenchi di contatti.<br/></p> 
<p>
  <ul class="list_homepage">
    <li>Avrai la nostra consulenza sulla creazione di elenchi di contatti adeguati tramite varie iniziative quali i concorsi a premi.</li>
	<li>A richiesta potrai usufruire del <b>servizio di inserimento/importazione di elenchi di contatti</b> con i relativi numeri di telefono ed eventuali dati anagrafici (rubrica). I dati possono essere forniti tramite schede cartacee, elenchi o file di qualsiasi tipo (excel, txt, word etc).  I contatti possono essere inseriti anche manualmente.</li>
	<li>Avrai la possibilità di utilizzare autonomamente un comodo pannello di amministrazione online  (<b>nessun software da installare</b>).</li>
	<li>Tramite il pannello è possibile inviare messaggi <b>SMS con testo personalizzato</b> a tutti i propri clienti o particolari gruppi di utenti. E’ possibile programmare e perfezionare con largo anticipo l’invio e solo quando si è sicuri procedere all’invio effettivo.</li>
	<li>Potrai memorizzare un <b>numero infinito di gruppi</b> ai quali associare i tuoi contatti.</li>
	<li>Potrai memorizzare un <b>numero infinito di contatti</b> nella rubrica e profilare i propri clienti secondo una qualsiasi combinazione di criteri quali, fasce di età, sesso, provincia, città o gruppo.</li>
	<li>La consegna dei messaggi SMS è garantita grazie al fatto che utilizziamo unicamente <b>messaggi di alta qualità con notifica di consegna</b>.</li>
	<li>Potrai <b>personalizzare il mittente</b> del messaggio SMS</li>
	<li>Ti proponiamo sin dalle prime fasi una formazione telefonica all’utilizzo del pannello di amministrazione per prendere confidenza con questo potente strumento.</li>
	<li>Avrai costante assistenza da parte dei nostri incaricati.</li>
  </ul>
</p>
<br/>
<br/>
<h1>Perch&egrave; Mister SMS ?</h1>
<ul class="list_homepage">
  <li>L'<b>SMS marketing</b> è uno di metodi più efficaci ed economici per impostare le tue campagne pubblicitarie o inviare <b>SMS informativi</b>.</li>
  <li>Il cellulare è lo strumento di comunicazione più diffuso al mondo, secondo alcune recenti ricerche dell’Eurostat (2009),  il paese europeo con la maggior diffusione di telefono cellulari è proprio l’Italia con una media di 1,22 telefonini per ogni italiano.</li>
  <li>Un SMS ha le caratteristiche di un <b>coupon elettronico</b> e può avere lo stesso valore di un coupon cartaceo da presentare in un negozio ma non occupa spazio nelle cassette delle lettere e non crea al destinatario fastidiosi ingombri come i volantini cartacei.</li>
  <li>Le normali campagne pubblicitarie attraverso i media (tv, radio, etc.), possono fallire se nel momento in cui avvengono il potenziale cliente è occupato o distratto. Un SMS costa meno dei media, giunge sempre a destinazione e il ricevente lo leggerà non appena ne avrà occasione, difficilmente le persone cancellano gli SMS senza averli letti.</li>
</ul>
<br/>
<br/>
<h1>Un servizio versatile</h1>
<p>Il servizio pu&ograve; essere utilizzato in maniera versatile per scopi commerciali ed informativi, ecco alcuni esempi:</p>
<ul class="list_homepage">
  <li>Esercizi commerciali: informare il cliente sulle offerte o sui nuovi arrivi, inviare coupon elettronici per accedere a scale di sconto</li>
  <li>Societ&agrave; di prestito finanziario: informare il cliente della scadenza di una rata o inviare semplici sms pubblicitari</li>
  <li>Pub, Discoteche: informare i clienti sugli eventi della serata, feste, inaugurazioni</li>
  <li>Biblioteche: informare il tesserato che il libro richiesto &egrave; arrivato o che il prestito sta per scadere</li>
  <li>Gli esempi d'uso sono tantissimi</li>
</ul>
<br/>
<p>Per conoscere <b>maggiori dettagli</b> sul servizio compila la form quì a lato oppure contattaci telefonicamente:</p>
<br></br>
<div id="big_phone_number"></div> 