<div class="box"> 
  <h2 id="solution">SMS Manager</h2> 
  <ul class="vertmenu"> 
    <li><a class="<?=$this->menu_item=="home"?"selected":""?>" href="<?=$this->url(array("action"=>"index"),"default")?>">Home page</a></li> 
    <li><a class="<?=$this->menu_item=="servizio"?"selected":""?>" href="<?=$this->url(array("action"=>"servizio"),"default")?>">Il servizio</a></li>
    <!--<li><a class="<?=$this->menu_item=="demo"?"selected":""?>" href="<?=$this->url(array("action"=>"demo"),"default")?>"><b>Demo</b> del servizio</a></li>  -->
    <li><a class="<?=$this->menu_item=="contatti"?"selected":""?>" href="<?=$this->url(array("action"=>"contatti"),"default")?>">Contatti</a></li>
  </ul>
</div>